### ISSUE TITLE
[Enhancement] game dvr and xbox live auth

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-core-node#25]
Are there any plans on including game DVR command into this and enabling auth to Xbox live, to get real name of the current application and some more information?

**Comment by unknownskl** [comment]
There are definitely plans to add more commands, however because i dont use them personally have not implemented them yet.
Which DVR commands would you like to see implemented?

Authentication against the xbox is in-progress at this moment. For getting title information i would suggest to look into this library: https://github.com/unknownskl/xbox-webapi-node (Warning: Still in POC state and no documentation is available yet)
In case you are looking for examples on how to use this together, you can check out this repository: https://github.com/unknownskl/xbox-smartglass-electron

Let me know if i can help you with anything. :-)

**Comment by foxriver76** [comment]
I wasn't aware of the webapi-node, thanks. ;-)
So my plans for the future are to switch from using the python rest server to your node module. We are maintaining an open source nodejs-based home automation middleware platform and installing python additionally isn't trivial for the casual user. Especially since 3.5 support is dropped in the rest server and many SBC's running Debian only use 3.5 natively. So my goal would be to keep the current functionality but to get rid of the rest server. I will see how far I can get with the combination of smartglass-core-node and webapi-node, thanks so far.

Game DVR is a feature which I also personally use to trigger recording of the previous minute of gameplay by speech assistant if something funny happened ;-) 
This is basically a GET request to the rest server by `http://${restServerAddress}:5557/device/${liveId}/gamedvr`. If you need further information let me know.

**Comment by unknownskl** [comment]
DVR Command has been implemented. Can be used as below:
`sgClient.recordGameDvr().then(function(status){
    console.log('DVR record send')
}).catch(function(error){
    console.log('DVR record error:', error)
})`

The current user must be authenticated. Yoou canpass the uhs and the xsts token via the connect command. Example below:
`sgClient.connect('192.168.2.5', uhs, xsts_token).then(function(){`

**Comment by foxriver76** [comment]
Thanks, I will check it ASAP ;-)
